name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@35470086eefff9eaed82eb7eb97c073866fea21d
      with:
        args: spdx
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@35470086eefff9eaed82eb7eb97c073866fea21d
      with:
        args: --include-submodules lint
