name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance check
      uses: fsfe/reuse-action@master
      with:
        cmd: lint
        arg: '--include-submodules'
