name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance check
      uses: fsfe/reuse-action@v0.2
      with:
        cmd: 'lint'
